CREATE TABLE tb_arquivo_doc (id_arquivo BIGINT NOT NULL, arquivo BYTEA, content_type VARCHAR(255), descricao VARCHAR(255), situacao INTEGER, PRIMARY KEY (id_arquivo));
CREATE TABLE tb_categoria (id_categoria BIGINT NOT NULL, descricao VARCHAR(255), situacao INTEGER, id_categoria_pai BIGINT, PRIMARY KEY (id_categoria));
CREATE TABLE tb_documento (id_documento BIGINT NOT NULL, data_documento TIMESTAMP, data_inclusao TIMESTAMP, data_ultima_alteracao TIMESTAMP, descricao VARCHAR(255), observacao VARCHAR(255), situacao INTEGER, id_arquivo BIGINT, id_categoria BIGINT, id_tipo_doc BIGINT, id_usuario BIGINT, PRIMARY KEY (id_documento));
CREATE TABLE tb_grupo_usuario (id_grupo_usuario BIGINT NOT NULL, grupo VARCHAR(255), situacao VARCHAR(255), PRIMARY KEY (id_grupo_usuario));
CREATE TABLE tb_pessoa (id_pessoa BIGINT NOT NULL, celular VARCHAR(255), cpf VARCHAR(255), email VARCHAR(255), nome VARCHAR(255), situacao VARCHAR(255), PRIMARY KEY (id_pessoa));
CREATE TABLE tb_tipo_doc (id_tipo_doc BIGINT NOT NULL, descricao VARCHAR(255), situacao INTEGER, PRIMARY KEY (id_tipo_doc));
CREATE TABLE tb_usuario (id_usuario BIGINT NOT NULL, role VARCHAR(255), senha VARCHAR(60) NOT NULL, situacao VARCHAR(255), usuario VARCHAR(45) NOT NULL UNIQUE, id_pessoa BIGINT, PRIMARY KEY (id_usuario));
CREATE TABLE rl_categoria_grupousuario (id_categoria BIGINT NOT NULL, id_grupo_usuario BIGINT NOT NULL, PRIMARY KEY (id_categoria, id_grupo_usuario));
CREATE TABLE rl_func_grupo_usuario (GrupoUsuario_id_grupo_usuario BIGINT, id_funcionalidade VARCHAR(255));
CREATE TABLE rl_tipo_func_grupo_usuario (GrupoUsuario_id_grupo_usuario BIGINT, id_permissao VARCHAR(255));
CREATE TABLE rl_grupousuario_usuario (id_grupo_usuario BIGINT NOT NULL, id_usuario BIGINT NOT NULL, PRIMARY KEY (id_grupo_usuario, id_usuario));
ALTER TABLE tb_categoria ADD CONSTRAINT tbctgriadctgriapai FOREIGN KEY (id_categoria_pai) REFERENCES tb_categoria (id_categoria);
ALTER TABLE tb_documento ADD CONSTRAINT tbdocumentodrquivo FOREIGN KEY (id_arquivo) REFERENCES tb_arquivo_doc (id_arquivo);
ALTER TABLE tb_documento ADD CONSTRAINT tbdocumentodsuario FOREIGN KEY (id_usuario) REFERENCES tb_usuario (id_usuario);
ALTER TABLE tb_documento ADD CONSTRAINT tbdcumentodtipodoc FOREIGN KEY (id_tipo_doc) REFERENCES tb_tipo_doc (id_tipo_doc);
ALTER TABLE tb_documento ADD CONSTRAINT tbdcmentodctegoria FOREIGN KEY (id_categoria) REFERENCES tb_categoria (id_categoria);
ALTER TABLE tb_usuario ADD CONSTRAINT tbusuarioid_pessoa FOREIGN KEY (id_pessoa) REFERENCES tb_pessoa (id_pessoa);
ALTER TABLE rl_categoria_grupousuario ADD CONSTRAINT rlctgrgrpsriodctgr FOREIGN KEY (id_categoria) REFERENCES tb_categoria (id_categoria);
ALTER TABLE rl_categoria_grupousuario ADD CONSTRAINT rlctgrgrpsrodgrpsr FOREIGN KEY (id_grupo_usuario) REFERENCES tb_grupo_usuario (id_grupo_usuario);
ALTER TABLE rl_func_grupo_usuario ADD CONSTRAINT rlfncgrGrpsrdgrpsr FOREIGN KEY (GrupoUsuario_id_grupo_usuario) REFERENCES tb_grupo_usuario (id_grupo_usuario);
ALTER TABLE rl_tipo_func_grupo_usuario ADD CONSTRAINT rltpfncGrpsrdgrpsr FOREIGN KEY (GrupoUsuario_id_grupo_usuario) REFERENCES tb_grupo_usuario (id_grupo_usuario);
ALTER TABLE rl_grupousuario_usuario ADD CONSTRAINT rlgrpsrsariodgrpsr FOREIGN KEY (id_grupo_usuario) REFERENCES tb_grupo_usuario (id_grupo_usuario);
ALTER TABLE rl_grupousuario_usuario ADD CONSTRAINT rlgrpsrousuariodsr FOREIGN KEY (id_usuario) REFERENCES tb_usuario (id_usuario);
CREATE SEQUENCE seq_arquivo_doc START WITH 1;
CREATE SEQUENCE seq_usuario START WITH 1;
CREATE SEQUENCE seq_documento START WITH 1;
CREATE SEQUENCE seq_grupo_usuario START WITH 1;
CREATE SEQUENCE seq_categoria START WITH 1;
CREATE SEQUENCE seq_pessoa START WITH 1;
CREATE SEQUENCE seq_tipo_doc START WITH 1;